export const icons = {
  add: { ios: 'ios-add-circle', android: 'add-circle' },
  save: { ios: 'ios-done', android: 'save' },
  close: { ios: 'ios-close', android: 'cancel' },
  wallet: { ios: 'ios-wallet', android: 'account-balance-wallet' },
  search: { ios: 'ios-search', android: 'search' },
  visibility: { ios: 'ios-eye', android: 'visibility' },
  'visibility-off': { ios: 'ios-eye-off', android: 'visibility-off' },
  // { name: 'car', iosIcon: 'ios-car', androidIcon: '' },
  // { name: 'bus', iosIcon: 'ios-bus' },
  // { name: 'airplane', iosIcon: 'ios-airplane' },
  // { name: 'basketball', iosIcon: 'ios-basketball' },
  // 'ios-appstore',
  // 'ios-beer',
  // 'ios-bed',
  // 'ios-body',
  // 'ios-bulb',
  // 'ios-cafe',
  // 'ios-book',
  // 'ios-call',
  // 'ios-business',
  // 'ios-brush',
  // 'ios-camera',
  // 'ios-cart',
  // 'ios-fitness',
  // 'ios-heart',
  // 'ios-home',
  // 'ios-key',
  // 'ios-gift',
  // 'ios-paw',
  // 'ios-pulse',
  // 'ios-school',
  // 'ios-shirt',
  // 'ios-subway',
  // 'ios-tv',
  // 'ios-bicycle',
  // 'ios-cloud',
  // 'ios-flower',
  // 'ios-nutrition',
  // 'ios-medical',
  // 'ios-restaurant',
  // 'ios-people',
  // 'ios-leaf',
  // 'ios-football',
  // 'ios-ice-cream',
  // 'ios-hammer',
  // 'ios-images',
  // 'ios-paper',
};
