export const icons = {
  'add-circle': { ios: 'ios-add-circle', android: 'add-circle' },
  save: { ios: 'ios-done', android: 'save' }, // Todo
  close: { ios: 'ios-close', android: 'cancel' },
  wallet: { ios: 'ios-wallet', android: 'account-balance-wallet' },
  search: { ios: 'ios-search', android: 'search' },
  visibility: { ios: 'ios-eye', android: 'visibility' },
  'visibility-off': { ios: 'ios-eye-off', android: 'visibility-off' },
  stats: { ios: 'ios-stats', android: 'insert-chart' },
  'list-box': { ios: 'ios-list-box', android: 'format-list-bulleted' },
  more: { ios: 'ios-more', android: 'more-vert' },
  'arrow-forward': { ios: 'ios-arrow-forward', android: 'arrow-forward' },
  settings: { ios: 'ios-settings', android: 'settings' },
  checkmark: { ios: 'ios-checkmark', android: 'check-circle' },
  warning: { ios: 'ios-warning', android: '' },
};

export const categoryIcons = {
  car: { ios: 'ios-car', android: 'directions-car' },
  bus: { ios: 'ios-bus', android: 'directions-bus' },
  airplane: { ios: 'ios-airplane', android: 'flight' },
  basketball: { ios: 'ios-basketball', android: '' },
  appstore: { ios: 'ios-appstore', android: '' },
  beer: { ios: 'ios-beer', android: '' },
  bed: { ios: 'ios-bed', android: '' },
  body: { ios: 'ios-body', android: '' },
  bulb: { ios: 'ios-bulb', android: '' },
  book: { ios: 'ios-book', android: '' },
  cafe: { ios: 'ios-cafe', android: '' },
  call: { ios: 'ios-call', android: '' },
  business: { ios: 'ios-business', android: '' },
  brush: { ios: 'ios-brush', android: '' },
  camera: { ios: 'ios-camera', android: '' },
  cart: { ios: 'ios-cart', android: '' },
  fitness: { ios: 'ios-fitness', android: '' },
  heart: { ios: 'ios-heart', android: '' },
  home: { ios: 'ios-home', android: '' },
  key: { ios: 'ios-key', android: '' },
  gift: { ios: 'ios-gift', android: '' },
  paw: { ios: 'ios-paw', android: '' },
  pulse: { ios: 'ios-pulse', android: '' },
  school: { ios: 'ios-school', android: '' },
  shirt: { ios: 'ios-shirt', android: '' },
  subway: { ios: 'ios-subway', android: '' },
  tv: { ios: 'ios-tv', android: '' },
  bicycle: { ios: 'ios-bicycle', android: '' },
  cloud: { ios: 'ios-cloud', android: '' },
  flower: { ios: 'ios-flower', android: '' },
  nutrition: { ios: 'ios-nutrition', android: '' },
  medical: { ios: 'ios-medical', android: '' },
  restaurant: { ios: 'ios-restaurant', android: '' },
  people: { ios: 'ios-people', android: '' },
  leaf: { ios: 'ios-leaf', android: '' },
  football: { ios: 'ios-football', android: '' },
  'ice-cream': { ios: 'ios-ice-cream', android: '' },
  hammer: { ios: 'ios-hammer', android: '' },
  images: { ios: 'ios-images', android: '' },
  paper: { ios: 'ios-paper', android: '' },
};
